### ISSUE TITLE
Moon image isn't loading

### ISSUE THREAD

**Issue by MorgulWWIV** [NolanKingdon/MMM-MoonPhase#17]
I've installed MMM-MoonPhase, but the detailed image isn't loading.  If I set it to basic, I get a simple white circle with the shadow superimposed on it, so the module is working.  However, if I set it to detailed, I get a blank image.  Looking in the developer tools, it's giving an error loading the image. 
I've verified that the image is there and that the MMM-MoonPhase.js script ss looking in the right place, as far as I can tell.  The error being given is a 404 error, but I don't know why.

Anyone have any thoughts?

**Comment by NolanKingdon** [comment]
Can you post a picture of the error message and the configuration for the module in the config file?

**Comment by MorgulWWIV** [comment]
I'm pretty sure the issue isn't anything to do with the module itself.  Something's preventing the module from accessing the file, but I don't know what.
I'm attaching screen shots of the error shown in the Dev Tools of MagicMirror2, the module entry in config.js, the relevant section in the MMM-MoonPhase.js, and the directory where my full.png is stored.
It may be something really simple that I'm overlooking, but hopefully someone will catch it.

![MoonPhase SS 3](https://user-images.githubusercontent.com/74803711/101098288-a97c7200-3590-11eb-863e-72839caf82d6.jpg)
![MoonPhase SS 2](https://user-images.githubusercontent.com/74803711/101098296-ad0ff900-3590-11eb-9b66-9e1a654b960e.png)
![MoonPhase SS 4](https://user-images.githubusercontent.com/74803711/101098308-b00ae980-3590-11eb-89d3-7e745ca1021f.png)
![MoonPhase SS 1](https://user-images.githubusercontent.com/74803711/101098312-b305da00-3590-11eb-837c-28dfc84bbe38.png)

**Comment by MorgulWWIV** [comment]
Issue has been resolved.  It took some experimenting, but I had to change the moonCanvas.style.background to "url('modules/MMM-MoonPhase/Phases/full.png?raw=true')"  and it worked.

So, I'm all good now!

**Comment by villasenor** [comment]
I also just ran into this on a fresh installation. It seems like this should "just work" by default. Any idea what the root cause of this issue is @NolanKingdon?

**Comment by NolanKingdon** [comment]
Probably the relative path messing things up. I made a [PR here](https://github.com/NolanKingdon/MMM-MoonPhase/pull/46). 

I unfortunately don't have a mirror or development environment in which to test anymore. If you could checkout the linked branch and let me know if that resolves things, I can merge.

**Comment by villasenor** [comment]
Got it working, but I did have to tweak your [PR](https://github.com/NolanKingdon/MMM-MoonPhase/pull/46) a bit. Added a comment there so you remember to change that before merging. Thanks for the quick response!
