### ISSUE TITLE
Style does not match default Magic Mirror module styles

### ISSUE THREAD

**Issue by Jakobud** [NolanKingdon/MMM-MoonPhase#19]
The module style CSS does not at all match the styles for the default Magic Mirror modules:

![image](https://user-images.githubusercontent.com/87356/155217736-d4c03029-339b-44d5-a2b2-040b4c59ee12.png)

For example the header is completely wrong. Wrong font, font size, color, <hr> color is wrong, justification is not correct, etc.

**Comment by NolanKingdon** [comment]
#29 aligns more with MagicMirror styles.
