### ISSUE TITLE
There is no issue, just a translation.

### ISSUE THREAD

**Issue by margamc** [NolanKingdon/MMM-MoonPhase#2]
Hi! 
First of all, thank you for the module for mm². I've translated the es.json file to spanish (my mother language). I let it here just in case you want to upload it. 

Thank you very much,
Marga.

PS. Sorry about the issue post, I don't know how to send you a message for that kind of topic.

[es.json.txt](https://github.com/NolanKingdon/MMM-MoonPhase/files/3471757/es.json.txt)

**Comment by NolanKingdon** [comment]
That's great, thank you! You should open up a Pull Request so the repo properly credits your contribution.
