### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by Antgr36** [NolanKingdon/MMM-MoonPhase#22]
Hello. I have my MM config.js locale and language set as "el" and not as "gr" because the locale code for Greek is el from what I found in web. Also default clock, Calendar and MMM-Weather works fine with that. Is it possible to rename it somehow or copy and merge it as "el"? Thank you in advance.

**Comment by NolanKingdon** [comment]
#34 to add code to point `el` to the existing greek translations
