### ISSUE TITLE
Kindly update the image without black background.

### ISSUE THREAD

**Issue by hrizvi-lifesize** [NolanKingdon/MMM-MoonPhase#3]
Please see if it is possible to remove black background from the moon image.

![full_no_background](https://user-images.githubusercontent.com/15894364/63458349-4b1d9580-c418-11e9-948f-2f144c3c85a0.png)
![full](https://user-images.githubusercontent.com/15894364/63458351-4bb62c00-c418-11e9-9066-ef40bc06670e.png)
![background](https://user-images.githubusercontent.com/15894364/63458352-4bb62c00-c418-11e9-81b3-5344aede068c.png)

**Comment by NolanKingdon** [comment]
This shouldn't be a huge issue. I'll take a look at it in the next few days and keep you updated.

**Comment by NolanKingdon** [comment]
I have updated draw method to no longer create the black shadowed box. I have also updated the moon image to remove the black corners.

Let me know if that has worked for you!

**Comment by hrizvi-lifesize** [comment]
Awesome, it worked wonderfully, many thanks.
