### ISSUE TITLE
Module does not update

### ISSUE THREAD

**Issue by boderg** [NolanKingdon/MMM-MoonPhase#30]
Hi, I have been using this module on my magic mirror for a while now. It used to work perfectly but since the last update this module will not update and change the phase and number of days unless I restart the magic mirror every day.

**Comment by NolanKingdon** [comment]
Hey - thanks for making an issue. I just merged #31 as an attempted fix.

Let me know if that resolves the issue.

**Comment by boderg** [comment]
Thanks, I will update today and give some feedback in a few days.

**Comment by boderg** [comment]
I have been running with the updated changes now for a few days and all seems to be running well and updating every day. Very nice module!
